"""Step 8 -- Validate Output.

Independently validates the generated dashboard against the LIVE database.

Independence rule: none of the queries below is taken from, or generated by,
`02_SQL/ebay_return_analysis.sql`. Every expected figure is derived here from
the base tables with its own query, and several are deliberately formulated
differently from the report (for example Main Return Reason is re-derived from
per-reason counts in Python rather than with `MODE()`), so that a fault in the
report query cannot reproduce itself in the check.

Coverage -- EVERY row of the report is checked on every one of these:

    Returns, Return Rate,
    Last Month Returns, Last Month Returns %,
    Last Year Returns,  Last Year Returns %,
    Refund (£), Last Month Refund (£), Return Cost (£), Main Return Reason,
    Return Rank, Negative Feedback, Open Cases, Stock,
    Ad Spend (£), Ad Sales (£), ACOS, ROAS

plus duplicate Listing ID + SKU detection, join fan-out detection, and a
render check that every value in the HTML is the value in the dataset.

All queries are read-only. Nothing is written to the source database.
"""
from __future__ import annotations

import html as htmllib
import json
import re

import psycopg

import config

# Market Place is shown under a business label; declared here independently of
# the builder so this stays a real check.
MARKET_PLACE_LABELS = {"EBAY_GB": "EBAY_UK"}

MONEY = {"Refund (£)", "Last Month Refund (£)", "Return Cost (£)",
         "Ad Spend (£)", "Ad Sales (£)"}
PERCENT = {"Return Rate", "Last Month Returns %", "Last Year Returns %", "ACOS"}
INTEGER = {"Total Orders", "Returns", "Last Month Returns", "Last Year Returns",
           "Negative Feedback", "Open Cases", "Stock"}


def _num(v):
    return 0 if v is None else v


def _close(a, b, tol) -> bool:
    if a is None and b is None:
        return True
    if a is None or b is None:
        return False
    return abs(a - b) <= tol


# ---------------------------------------------------------------------------
# Independent source queries -- one per measure, written from the base tables
# ---------------------------------------------------------------------------
_RETURNS_BY_KEY = """
SELECT r.item_id::text,
       COALESCE(NULLIF(oi.real_sku, ''), oi.item_sku),
       COUNT(DISTINCT r.return_id),
       ROUND(SUM(COALESCE(r.seller_refund_amount, 0))::numeric, 2),
       COUNT(DISTINCT r.return_id) FILTER (WHERE r.current_state IS DISTINCT FROM 'CLOSED')
  FROM customer_service.ebay_returns r
  JOIN order_management.order_item_info oi
    ON oi.item_transaction_id = r.transaction_id
 WHERE r.res_his_order = 0
   AND r.request_date >= %s AND r.request_date < %s
 GROUP BY 1, 2
"""

_REASON_COUNTS = """
SELECT r.item_id::text,
       COALESCE(NULLIF(oi.real_sku, ''), oi.item_sku),
       r.reason,
       COUNT(*)
  FROM customer_service.ebay_returns r
  JOIN order_management.order_item_info oi
    ON oi.item_transaction_id = r.transaction_id
 WHERE r.res_his_order = 0
   AND r.request_date >= %s AND r.request_date < %s
 GROUP BY 1, 2, 3
"""

_UNITS_BY_KEY = """
SELECT oi.item_id,
       COALESCE(NULLIF(oi.real_sku, ''), oi.item_sku),
       SUM(COALESCE(NULLIF(oi.item_quantity, '')::numeric, 0))
  FROM order_management.orders o
  JOIN order_management.sub_source ss ON ss.id = o.sub_source_id
  JOIN order_management.source     s  ON s.id  = ss.source_id AND s.source_name = 'EBAY'
  JOIN order_management.order_item_info oi ON oi.order_id = o.id
 WHERE o.order_date >= %s AND o.order_date < %s
 GROUP BY 1, 2
"""

_RETURN_COST = """
SELECT t.item_id::text,
       t.sku,
       ROUND(SUM(COALESCE(e.fee, 0))::numeric, 2)
  FROM (SELECT DISTINCT r.item_id,
               COALESCE(NULLIF(oi.real_sku, ''), oi.item_sku) AS sku,
               r.transaction_id
          FROM customer_service.ebay_returns r
          JOIN order_management.order_item_info oi
            ON oi.item_transaction_id = r.transaction_id
         WHERE r.res_his_order = 0
           AND r.request_date >= %s AND r.request_date < %s) t
  JOIN accounting.ebay_order_expenses e ON e.item_id::text = t.transaction_id
 WHERE e.transaction_type = 'REFUND'
   AND e.fee_type IN ('FINAL_VALUE_FEE', 'FINAL_VALUE_FEE_FIXED_PER_ORDER')
 GROUP BY 1, 2
"""

_NEG_FEEDBACK = """
SELECT oi.item_id,
       COALESCE(NULLIF(oi.real_sku, ''), oi.item_sku),
       COUNT(*)
  FROM customer_service.ebay_orders_customer_feedbacks f
  JOIN order_management.order_item_info oi
    ON oi.item_transaction_id = f.transaction_id
 WHERE f.type = 'Negative'
   AND f.date >= %s AND f.date < %s
 GROUP BY 1, 2
"""

_STOCK = """
SELECT pr.sku, SUM(COALESCE(st.stock, 0))
  FROM inventory.products pr
  JOIN inventory.local_inventory_current_stock_location_wise st
    ON st.inventory_id = pr.id
 GROUP BY 1
"""

_ADS_BY_LISTING = """
SELECT pd.ebay_listing_id::text,
       ROUND(SUM(COALESCE(pd.ad_fees_listing_currency, 0))::numeric, 2),
       ROUND(SUM(COALESCE(pd.sale_amount_listing_currency, 0))::numeric, 2)
  FROM ebay_campaigns.performance_data pd
 WHERE pd.date >= %s AND pd.date < %s
 GROUP BY 1
"""


def _fetch(cur, sql, params):
    cur.execute(sql, params)
    return cur.fetchall()


def run(payload: dict, period: config.Period, log) -> dict:
    rows = payload["rows"]
    columns = payload["columns"]
    lits = period.sql_literals()
    P = (lits["p_start"], lits["p_end"])
    LM = (lits["lm_start"], lits["lm_end"])
    LY = (lits["ly_start"], lits["ly_end"])

    results: list[tuple[str, str, str]] = []

    def check(name: str, ok: bool, detail: str = "") -> None:
        results.append((name, "PASS" if ok else "FAIL", detail))

    keys = [(r["Listing ID"], r["SKU"]) for r in rows]

    # ======================================================================
    # A. Grain and fan-out
    # ======================================================================
    check("No duplicate Listing ID + SKU rows",
          len(keys) == len(set(keys)),
          f"{len(rows)} rows, {len(set(keys))} distinct Listing ID + SKU keys")

    with psycopg.connect(config.source_db_url(),
                         connect_timeout=config.DB_CONNECT_TIMEOUT) as conn:
        conn.read_only = True
        cur = conn.cursor()
        cur.execute(f"SET statement_timeout = {config.DB_STATEMENT_TIMEOUT_MS}")

        for label, window in (("reporting", P), ("last month", LM), ("last year", LY)):
            cur.execute(
                "SELECT COUNT(*), COUNT(DISTINCT r.return_id) "
                "FROM customer_service.ebay_returns r "
                "JOIN order_management.order_item_info oi "
                "  ON oi.item_transaction_id = r.transaction_id "
                "WHERE r.res_his_order = 0 "
                "  AND r.request_date >= %s AND r.request_date < %s", window)
            joined, distinct = cur.fetchone()
            check(f"No join fan-out, {label} window ({window[0]} to {window[1]})",
                  joined == distinct,
                  f"{joined} joined rows = {distinct} distinct returns")

        # ==================================================================
        # B. Independent per-key measures
        # ==================================================================
        cur_returns = {(l, s): (n, float(ref), op)
                       for l, s, n, ref, op in _fetch(cur, _RETURNS_BY_KEY, P)}
        lm_returns = {(l, s): (n, float(ref), op)
                      for l, s, n, ref, op in _fetch(cur, _RETURNS_BY_KEY, LM)}
        ly_returns = {(l, s): (n, float(ref), op)
                      for l, s, n, ref, op in _fetch(cur, _RETURNS_BY_KEY, LY)}

        # Main Return Reason re-derived in Python from per-reason counts, NOT MODE().
        reason_tally: dict[tuple, dict[str, int]] = {}
        for l, s, reason, n in _fetch(cur, _REASON_COUNTS, P):
            reason_tally.setdefault((l, s), {})[reason] = n

        units_p = {(str(l), s): float(q) for l, s, q in _fetch(cur, _UNITS_BY_KEY, P)}
        units_lm = {(str(l), s): float(q) for l, s, q in _fetch(cur, _UNITS_BY_KEY, LM)}
        units_ly = {(str(l), s): float(q) for l, s, q in _fetch(cur, _UNITS_BY_KEY, LY)}

        return_cost = {(l, s): float(c) for l, s, c in _fetch(cur, _RETURN_COST, P)}
        neg_fb = {(str(l), s): n for l, s, n in _fetch(cur, _NEG_FEEDBACK, P)}
        stock = {sku: float(q) for sku, q in _fetch(cur, _STOCK, ())}
        ads = {l: (float(sp), float(sa)) for l, sp, sa in _fetch(cur, _ADS_BY_LISTING, P)}

        # Independent grand totals, straight off the returns table.
        cur.execute(
            "SELECT COUNT(DISTINCT return_id), "
            "       ROUND(SUM(COALESCE(seller_refund_amount,0))::numeric,2), "
            "       COUNT(DISTINCT return_id) FILTER "
            "            (WHERE current_state IS DISTINCT FROM 'CLOSED') "
            "  FROM customer_service.ebay_returns "
            " WHERE res_his_order = 0 "
            "   AND request_date >= %s AND request_date < %s", P)
        db_returns, db_refund, db_open = cur.fetchone()

        window_totals = {}
        for key, window in (("period", P), ("last_month", LM), ("last_year", LY)):
            cur.execute(
                "SELECT COUNT(DISTINCT return_id) FROM customer_service.ebay_returns "
                "WHERE res_his_order = 0 "
                "  AND request_date >= %s AND request_date < %s", window)
            window_totals[key] = cur.fetchone()[0]

    # ======================================================================
    # C. Row-by-row comparison -- every row, every measure
    # ======================================================================
    mismatches: dict[str, list[str]] = {}

    def record(column: str, key, got, want) -> None:
        mismatches.setdefault(column, []).append(f"{key[0]}/{key[1]}: {got!r} != {want!r}")

    # Per-listing period units, for the pro-rata ad allocation.
    listing_units: dict[str, float] = {}
    rows_per_listing: dict[str, int] = {}
    for (l, s) in keys:
        rows_per_listing[l] = rows_per_listing.get(l, 0) + 1
    for (l, s), q in units_p.items():
        listing_units[l] = listing_units.get(l, 0.0) + q

    for r in rows:
        key = (r["Listing ID"], r["SKU"])

        # --- Returns -------------------------------------------------------
        want_returns = cur_returns.get(key, (0, 0.0, 0))
        if r["Returns"] != want_returns[0]:
            record("Returns", key, r["Returns"], want_returns[0])

        # --- Refund (£) ----------------------------------------------------
        if not _close(_num(r["Refund (£)"]), want_returns[1], config.MONEY_TOLERANCE):
            record("Refund (£)", key, r["Refund (£)"], want_returns[1])

        # --- Open Cases ----------------------------------------------------
        if r["Open Cases"] != want_returns[2]:
            record("Open Cases", key, r["Open Cases"], want_returns[2])

        # --- Total Orders and Return Rate ----------------------------------
        want_units = units_p.get(key, 0.0)
        if not _close(float(r["Total Orders"]), want_units, 0.001):
            record("Total Orders", key, r["Total Orders"], want_units)
        want_rate = (round(want_returns[0] / want_units * 100, 2)
                     if want_units > 0 else None)
        if not _close(r["Return Rate"], want_rate, config.RATE_TOLERANCE):
            record("Return Rate", key, r["Return Rate"], want_rate)

        # --- Last Month Returns / % / Refund -------------------------------
        want_lm = lm_returns.get(key, (0, 0.0, 0))
        if r["Last Month Returns"] != want_lm[0]:
            record("Last Month Returns", key, r["Last Month Returns"], want_lm[0])
        if not _close(_num(r["Last Month Refund (£)"]), want_lm[1], config.MONEY_TOLERANCE):
            record("Last Month Refund (£)", key, r["Last Month Refund (£)"], want_lm[1])
        lm_units = units_lm.get(key, 0.0)
        want_lm_pct = round(want_lm[0] / lm_units * 100, 2) if lm_units > 0 else None
        if not _close(r["Last Month Returns %"], want_lm_pct, config.RATE_TOLERANCE):
            record("Last Month Returns %", key, r["Last Month Returns %"], want_lm_pct)

        # --- Last Year Returns / % -----------------------------------------
        want_ly = ly_returns.get(key, (0, 0.0, 0))
        if r["Last Year Returns"] != want_ly[0]:
            record("Last Year Returns", key, r["Last Year Returns"], want_ly[0])
        ly_units = units_ly.get(key, 0.0)
        want_ly_pct = round(want_ly[0] / ly_units * 100, 2) if ly_units > 0 else None
        if not _close(r["Last Year Returns %"], want_ly_pct, config.RATE_TOLERANCE):
            record("Last Year Returns %", key, r["Last Year Returns %"], want_ly_pct)

        # --- Return Cost (£) -----------------------------------------------
        want_cost = return_cost.get(key, 0.0)
        if not _close(_num(r["Return Cost (£)"]), want_cost, config.MONEY_TOLERANCE):
            record("Return Cost (£)", key, r["Return Cost (£)"], want_cost)

        # --- Main Return Reason (re-derived, not MODE()) ---------------------
        tally = reason_tally.get(key, {})
        want_reason = (sorted(tally.items(), key=lambda kv: (-kv[1], kv[0]))[0][0]
                       if tally else None)
        if r["Main Return Reason"] != want_reason:
            record("Main Return Reason", key, r["Main Return Reason"], want_reason)

        # --- Negative Feedback ----------------------------------------------
        want_neg = neg_fb.get(key, 0)
        if r["Negative Feedback"] != want_neg:
            record("Negative Feedback", key, r["Negative Feedback"], want_neg)

        # --- Stock -----------------------------------------------------------
        want_stock = stock.get(r["SKU"])
        if want_stock is None:
            if r["Stock"] is not None:
                record("Stock", key, r["Stock"], None)
        elif not _close(float(_num(r["Stock"])), want_stock, 0.001):
            record("Stock", key, r["Stock"], want_stock)

        # --- Ad Spend / Ad Sales (listing total x this row's unit share) -----
        listing_spend, listing_sales = ads.get(r["Listing ID"], (0.0, 0.0))
        lu = listing_units.get(r["Listing ID"], 0.0)
        share = (want_units / lu) if lu > 0 else 1.0 / rows_per_listing[r["Listing ID"]]
        want_spend = round(listing_spend * share, 2)
        want_sales = round(listing_sales * share, 2)
        if not _close(_num(r["Ad Spend (£)"]), want_spend, config.AD_TOLERANCE):
            record("Ad Spend (£)", key, r["Ad Spend (£)"], want_spend)
        if not _close(_num(r["Ad Sales (£)"]), want_sales, config.AD_TOLERANCE):
            record("Ad Sales (£)", key, r["Ad Sales (£)"], want_sales)

        # --- ACOS / ROAS, from the row's own displayed ad figures -------------
        spend, sales = r["Ad Spend (£)"], r["Ad Sales (£)"]
        want_acos = round(spend / sales * 100, 2) if (spend and sales) else None
        want_roas = round(sales / spend, 2) if (spend and sales) else None
        if spend and sales:
            if not _close(r["ACOS"], want_acos, config.AD_TOLERANCE):
                record("ACOS", key, r["ACOS"], want_acos)
            if not _close(r["ROAS"], want_roas, config.AD_TOLERANCE):
                record("ROAS", key, r["ROAS"], want_roas)

    # --- Return Rank, recomputed over the whole report ---------------------
    ordered = sorted(rows, key=lambda r: (-r["Returns"], -_num(r["Refund (£)"])))
    prev_key, prev_rank, bad_rank = None, 0, 0
    for i, r in enumerate(ordered, 1):
        k = (r["Returns"], _num(r["Refund (£)"]))
        expected = prev_rank if k == prev_key else i
        if r["Return Rank"] != expected:
            bad_rank += 1
        prev_key, prev_rank = k, expected

    for column in ("Returns", "Return Rate", "Total Orders",
                   "Last Month Returns", "Last Month Returns %", "Last Month Refund (£)",
                   "Last Year Returns", "Last Year Returns %",
                   "Refund (£)", "Return Cost (£)", "Main Return Reason",
                   "Negative Feedback", "Open Cases", "Stock",
                   "Ad Spend (£)", "Ad Sales (£)", "ACOS", "ROAS"):
        bad = mismatches.get(column, [])
        check(f"{column} matches the live database on all {len(rows)} rows",
              not bad,
              f"{len(bad)} mismatched row(s)" + (f", e.g. {bad[:2]}" if bad else ""))

    check(f"Return Rank = RANK() by Returns desc, Refund desc on all {len(rows)} rows",
          bad_rank == 0, f"{bad_rank} mismatched row(s)")

    # ======================================================================
    # D. Independent grand totals
    # ======================================================================
    report_returns = sum(r["Returns"] for r in rows)
    check("Returns total = direct DB count",
          report_returns == db_returns, f"report {report_returns} vs DB {db_returns}")
    report_refund = round(sum(_num(r["Refund (£)"]) for r in rows), 2)
    check("Refund (£) total = direct DB sum",
          _close(report_refund, float(db_refund), config.MONEY_TOLERANCE),
          f"report {report_refund} vs DB {db_refund}")
    report_open = sum(r["Open Cases"] for r in rows)
    check("Open Cases total = direct DB count",
          report_open == db_open, f"report {report_open} vs DB {db_open}")

    for key, total in window_totals.items():
        got = sum(k["returns"] for k in payload["kpi_windows"]
                  if k["window_key"] == key)
        check(f"KPI window '{key}' = direct DB count for that month",
              got == total, f"payload {got} vs DB {total}")

    check("KPI 'this month' total = the Returns column total",
          sum(k["returns"] for k in payload["kpi_windows"]
              if k["window_key"] == "period") == report_returns,
          f"{report_returns} returns")

    # ======================================================================
    # E. The rendered HTML says exactly what the dataset says
    # ======================================================================
    doc = config.STAGING_HTML.read_text(encoding="utf-8")

    def shown(row):
        label = MARKET_PLACE_LABELS.get(row["Market Place"])
        return dict(row, **{"Market Place": label}) if label else row

    shown_rows = [shown(r) for r in rows]

    head_html = re.search(r"<thead>(.*?)</thead>", doc, re.S).group(1)
    headers = [htmllib.unescape(h)
               for h in re.findall(r"<th[^>]*>(.*?)</th>", head_html, re.S)]
    check("HTML header row = the required columns, in order, nothing extra",
          headers == columns, f"{len(headers)} headers")

    body_html = re.search(r"<tbody>(.*?)</tbody>", doc, re.S).group(1)
    all_tr = re.findall(r"<tr\b([^>]*)>(.*?)</tr>", body_html, re.S)
    tr = [inner for a, inner in all_tr if "no-match" not in a]
    check("HTML row count = dataset row count",
          len(tr) == payload["row_count"],
          f"{len(tr)} rendered vs {payload['row_count']} in dataset")

    def expected_cell(column, value):
        if value is None:
            return ""
        if column in MONEY:
            return f"£{value:,.2f}"
        if column in PERCENT:
            return f"{value:,.2f}%"
        if column == "ROAS":
            return f"{value:,.2f}"
        if column == "Return Rank":
            return f"#{value}"
        if column in INTEGER:
            return f"{value:,.0f}"
        return str(value)

    render_bad = []
    for row_html, row in zip(tr, shown_rows):
        cells = [htmllib.unescape(c)
                 for c in re.findall(r"<td[^>]*>(.*?)</td>", row_html, re.S)]
        if len(cells) != len(columns):
            render_bad.append(f'{row["SKU"]}: {len(cells)} cells')
            continue
        for column, rendered in zip(columns, cells):
            want = expected_cell(column, row[column])
            if rendered != want:
                render_bad.append(f'{row["SKU"]}/{column}: "{rendered}" != "{want}"')
    check("Every rendered HTML cell equals its validated dataset value",
          not render_bad,
          f"{len(render_bad)} mismatch(es)" + (f", e.g. {render_bad[:2]}" if render_bad else ""))

    external = re.findall(r'(?:src|href)\s*=\s*"(?!#)([^"]+)"', doc)
    check("Standalone: no external src/href, fetch, XHR or @import",
          not external
          and not re.search(r"<script[^>]*\ssrc\s*=", doc, re.I)
          and not re.search(r"fetch\s*\(", doc, re.I)
          and not re.search(r"XMLHttpRequest", doc)
          and not re.search(r"@import", doc, re.I),
          f"{len(external)} external reference(s)")

    forbidden = [m for m in config.FORBIDDEN_HTML_MARKERS if m in doc]
    check("No credential, placeholder or bad value in the HTML",
          not forbidden, f"found: {forbidden}" if forbidden else "none")

    # The header must state the period this run actually calculated.
    for label, text in (("Reporting period", period.reporting_period),
                        ("Last month", period.last_month_period),
                        ("Last year", period.last_year_period)):
        check(f"HTML header states the calculated {label.lower()}",
              f"{label} {text}" in doc, text)

    check("Exactly three KPI cards, all labelled Returns",
          len(re.findall(r'<div class="kpi">', doc)) == 3
          and len(re.findall(r'<span class="kpi-unit">Returns</span>', doc)) == 3,
          f'{len(re.findall(chr(60) + "div class=" + chr(34) + "kpi" + chr(34) + chr(62), doc))} cards')

    check("Controls are exactly the four approved filters + Reset",
          sorted(re.findall(r'<(?:input|select|button)\b[^>]*\bid="([^"]+)"', doc))
          == ["f-account", "f-listing", "f-market", "f-reset", "f-sku"],
          "Account, Market Place, SKU, Listing ID, Reset")

    check("No chart / canvas / svg element",
          not re.search(r"<(canvas|svg)\b", doc, re.I), "")

    # ======================================================================
    # F. Verdict
    # ======================================================================
    failed = [r for r in results if r[1] == "FAIL"]
    status = "FAIL" if failed else "PASS"

    for name, verdict, detail in results:
        (log.error if verdict == "FAIL" else log.info)(
            f"   {verdict}  {name}{(' - ' + detail) if detail else ''}")

    log.metric("validation_checks", f"{len(results) - len(failed)}/{len(results)} passed")
    log.metric("validation_result", status)

    outcome = {
        "status": status,
        "checks_total": len(results),
        "checks_passed": len(results) - len(failed),
        "rows_validated": len(rows),
        "failures": [{"check": n, "detail": d} for n, v, d in results if v == "FAIL"],
        "execution_date": period.execution_date.isoformat(),
        "reporting_month": period.month_key,
        "reporting_period": period.reporting_period,
        "last_month_period": period.last_month_period,
        "last_year_period": period.last_year_period,
    }
    config.STAGING_VALIDATION.write_text(json.dumps(outcome, indent=2), encoding="utf-8")
    _write_evidence(period, payload, results, status, log)

    if failed:
        raise RuntimeError(
            f"output validation FAILED: {len(failed)} check(s) - "
            + "; ".join(n for n, _, _ in failed[:5]))

    return outcome


def _write_evidence(period, payload, results, status, log) -> None:
    failed = sum(1 for r in results if r[1] == "FAIL")
    lines = [
        "# Return Analysis - automated output validation (Step 8)", "",
        f"- Execution date: {period.execution_date}",
        f"- Reporting month: **{period.month_label}** ({period.reporting_period})",
        f"- Last Month: {period.last_month_label} ({period.last_month_period})",
        f"- Last Year: {period.last_year_label} ({period.last_year_period})",
        f"- Rows validated: **{payload['row_count']}** (all of them)",
        f"- Source: `{payload['source_database']}` (read-only), "
        f"snapshot {payload['snapshot_utc']}",
        f"- Result: **{status}** "
        f"({len(results) - failed}/{len(results)} checks passed)", "",
        "Every expected figure below was derived from the base tables with a query "
        "written for this check alone. The report query in "
        "`02_SQL/ebay_return_analysis.sql` was not reused, and Main Return Reason "
        "is re-derived from per-reason counts rather than with `MODE()`.", "",
        "| # | Check | Result | Detail |", "|---|---|---|---|",
    ]
    for i, (name, verdict, detail) in enumerate(results, 1):
        lines.append(f"| {i} | {name} | **{verdict}** | {detail} |")
    config.AUTOMATION_VALIDATION_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info(f"   evidence -> {config.AUTOMATION_VALIDATION_MD.name}")
